<font color="green">*To start working on this notebook, or any other notebook that we will use in this course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

# Python Programming: For Loops

## 1.0 Overview

In [1]:
# Example 1
# For loops are used to iterate over a sequence (i.e. list, dictionary, string etc.) 
# then perform some action.
# In this example, we will start to learn about for loops by iterating through a python list
# We will define this list as kenyan_football_players
#

# Defining our python list

kenyan_football_players = ["Victor Wanyama", "Michael Olunga", "McDonald Mariga"]

# printing the list out
print(kenyan_football_players)

# then using a for loop to iterate through the list
for x in kenyan_football_players:
  print(x)

# Let's look at what the above line of code does...
# The for loop goes inside the kenyan_football_players list, picks up the first 
#element (which is Victor Wanyama), it then stores it in a temporary variable x. 
#Once stored, it then prints out the value inside the variable x.
# After printing the value of x, it goes in the list again and picks the second 
#element(this time it's Michael Olunga), it stores this element inside the variable x again
#but this  time it replaces the value of x that was stored the first time. 
#After storing the new value of x, it goes ahead and print the new value of x.
# It repeats this process until all the elements in the list are printed out.
# The process of going through each element in a list is called iteration.
# Note: The x in the for loop, is only a temporary variable and you can name it anything you like 
# (you are not limited to only using x).
# Please take note of the print statement in the above lines of code. 
#You'll notice that its indented. This tells python that that line of code is inside the 
#for loop hence its the body of the loop. What this means is that it should be executed 
#every time the loop iterates through the list. 
# If we were to remove the indentation, then it would mean that the print statement is 
#outside the for loop hence the loop would do nothing once it iterates through the list.
# Once we run the code it would display an error.

['Victor Wanyama', 'Michael Olunga', 'McDonald Mariga']
Victor Wanyama
Michael Olunga
McDonald Mariga

In [2]:
# Example 2
# We can also create and iterate over a list called fruits
# from our learnings above

# Creating our python list
fruits = ["bananas", "grapes", "mangoes"]

# printing the list out
print(fruits)

# Use a for loop to iterate through the fruits list and print out each element in the list.
for x in fruits:
  print(x)

['bananas', 'grapes', 'mangoes']
bananas
grapes
mangoes

In [3]:
# Example 3
# Let's now create a dictionary and iterate over it
# Looping through a dictionary is slightly different from looping through a list. This is because a dictionary 
#is comprised of key-value pairs.
# There are several ways of looping through a dictionary. We will only look at a couple of them here

# Creating our dictionary
our_class = {
    'Name': '7 East', 
    'Students': 27, 
    'Wing': 'East'
}



# Looping through keys only
for x in our_class:
  print(x)

# This way of looping through a dictionary will only output the dictionary keys only. But what 
#if we wanted to display the key value pair?
print("****************************************************") 
# separating the two ways of looping
# To be able to achieve this, we are going to make us of a python's dictionary in-built function .items(). 
#This function will allow us to access the key-value pair at the same time.

for x,y in our_class.items():
  print(x,":", y)

# In the above lines of code, we are creating two temporary variables,x and y, 
#where x is used to store the key element and y stores the value element. 
#Then printing out the key-value pair of each dictionary elements.
# You can read more on how to loop through dictionaries here: https://realpython.com/iterate-through-dictionary-python/

Name
Students
Wing
****************************************************
Name : 7 East
Students : 27
Wing : East

### <font color="green">1.0 Challenges </font>

In [4]:
# Challenge 1
# Given the dictionary below, use a for loop to iterate over it
#

# Creating our dictionary
stocks = {
    'Safaricom PLC': 146.48,
    'KCB':44.11,
    'National Bank':25.54
}

for x,y in stocks.items():
  print(x,":", y)

Safaricom PLC : 146.48
KCB : 44.11
National Bank : 25.54

In [5]:
# Challenge 2
# Iterate over a list of dictionaries using a for loop
#

# Creating our list
values = [{"name": "Kevin", "food": "Chappati"}, {"name": "Ruth", "food": "Pilau"}]

for x in values:
  print(x)

{'name': 'Kevin', 'food': 'Chappati'}
{'name': 'Ruth', 'food': 'Pilau'}

In [1]:
# Challenge 3 
# Write a program that stores the values in a dictionary and 
# finds the average of values entered by a user. 
# The user will enter 0 to indicate that no further values will be provided. 
#
figures = dict()
counter = 0
user_input = 0

while True:
  counter = counter + 1
  user_input = int(input('Enter your figure {0} '.format(counter)))
  if user_input != 0:
    figures["value {0}".format(counter)] = user_input
  else:
    break
  
print('No more figures can be entered ')
print(figures)
print("sum: ", sum(figures.values()))
print("length of dictionary: ",len(figures))
print("average: ", (sum(figures.values()))/len(figures))

Enter your figure 1 5
Enter your figure 2 6
Enter your figure 3 8
Enter your figure 4 9
Enter your figure 5 0
No more figures can be entered
{'value 1': 5, 'value 2': 6, 'value 3': 8, 'value 4': 9}
sum:  28
length of dictionary:  4
average:  7.0

In [1]:
print("Input some integers to calculate their sum and average. Input 0 to exit.")

count = 0
sum = 0.0
number = 1

while number != 0:
	number = int(input(""))
	sum = sum + number
	count += 1

if count == 0:
	print("Input some numbers")
else:
	print("Average and Sum of the above numbers are: ", sum / (count-1), sum)

Input some integers to calculate their sum and average. Input 0 to exit.
5
6
7
0
Average and Sum of the above numbers are:  6.0 18.0

## 1.1 Looping Through a String

In [2]:
# Example 1
# For loops can also used for iterating over a string as shown; 
# Iterating through the string "moringa"
# The logic behind it is pretty much the same as that of looping through lists.

for y in "moringa":
  print(y)

m
o
r
i
n
g
a

In [3]:
# Example 2
# Lets iterate through your name below.
# Replace OUR CODE GOES HERE with you name;
#

for y in "Brian":
  print(y)

B
r
i
a
n

In [4]:
# Example 3
# Iterate through the following string
# 

greetings = "Hello everyone!"

for g in greetings:
    print(g)

H
e
l
l
o

e
v
e
r
y
o
n
e
!

### <font color="green">1.1 Challenges</font>

In [5]:
# Challenge 1
# Iterate through the string "Nairobi"
#
for y in "Nairobi":
  print(y)

N
a
i
r
o
b
i

In [6]:
# Challenge 2
# Print out the characters that make up the value of fruit as shown
#

fruit = 'banana'

for y in fruit:
  print(y)

b
a
n
a
n
a

In [4]:
# Challenge 3
# A user is prompted to provide a string (i.e. single or multiple strings) by the program.
# Create a program that tell us the number of times the letter "b" appears in the user inut. 
# Upon determination the program should display the number of times the letter appears in the user input.
# For example, if the user inputs the string bubbles. The program should output a message like; 
# The letter b has occured 3 times in your string. 
# 
# Hint: you will be required to use for loops and your knowledge of conditional statements to achieve the desired output.
#

l = input("Enter a string or strings containing letter b:")
count=0
for letter in l:
  if letter == "b":
    count+=1
print("The number of letter b in your string is:", count)

Enter a string or strings containing letter b:brian
The number of letter b in your string is: 1

## 1.2 The Break Statement

In [8]:
# Example 1
# We can use the break statement to stop the loop before it continues iterating though all items;
# Using the fruits list we can stop the loop 
# before it continues iterating through all items by
#

fruits = ["bananas", "grapes", "mangoes"]

for x in fruits:
  print(x) 
  if x == "grapes":
    break

bananas
grapes

In [9]:
# Example 2
# We can also use the break statement during the iteration of a string a shown
# 

for val in "Moringa School":
    if val == "i":
        break
    print(val)
print("The end")

M
o
r
The end

In [10]:
# Example 3
# Iterating through a string and breaking whenever the no. 98 is found
# 
for num in [21, 29, 98, 20, 100, 13, 29]: 
   print(num)
   if(num == 98):
	   print("The number 98 is found") 
	   break

21
29
98
The number 98 is found

### <font color="green">1.2 Challenges</font>

In [11]:
# Challenge 1 
# Using the kenyan_football_players dictionary let's stop the loop 
# before it continues iterating through all items
# 
kenyan_football_players = ["Victor Wanyama", "Michael Olunga", "McDonald Mariga"]
for x in kenyan_football_players:
  print(x)
  if x == "Michael Olunga":
    break

Victor Wanyama
Michael Olunga

In [22]:
# Challenge 2
# When you run the following code it should output
# "Sum of first 5 integers is: 15"
# Correct the following for loop and a add a break statement to ensure that the program 
#gives out the correct output
#

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9] # Declaring the tuple
num_sum = 0
count = 0
for y in numbers:
    num_sum = num_sum + y
    count = count + 1 
    if count == 5: 
      break      
  
print("Sum of first ",count,"integers is: ", num_sum)

Sum of first  5 integers is:  15

In [55]:
# Example 3
# Sarova Nairobi determines the price of admission based on the age of the guest. 
# Guests that are 2 years of age or less are admitted without charge. 
# Children between 3 and 12 years of age are charged Ksh. 15,000 a night. 
# Seniors aged 65 years and over are charged Ksh. 18,000 a night.
# Admission for all other guests is Ksh. 25,000 a night.
# Create a program that begins by reading the ages of all of the guests 
# in a group from the user, with ones age entered on each line. 
# The user will enter a blank line to indicate that there are no more guests in the group. 
# Then your program should display the admission cost for the group with an appropriate message. 
# The cost should be displayed using two decimal places. 
# NB: You should use a for loop and a break statement in your program.
# 

lst = []
 
n = int(input("Enter number of Guests : "))
for i in range(0,n):
    ele =int(input("Enter Age:"))
    lst.append(ele)
    if i ==" ":
      break
for x in lst:
  
  if x <2:
    print("For", x ,"years, the charge is Zero")
  elif x >2 and x <13:
    print ("For", x ,"years, the charge is Ksh 15,000" )
  elif x >65:
    print ("For", x ,"years, the charge is Ksh 18,000")
  else:
    print("For", x, "years, the charge is Ksh 25,000")

Enter number of Guests : 5
Enter Age:6
Enter Age:7
Enter Age:89
Enter Age:65
Enter Age:40
For 6 years, the charge is Ksh 15,000
For 7 years, the charge is Ksh 15,000
For 89 years, the charge is Ksh 18,000
For 65 years, the charge is Ksh 25,000
For 40 years, the charge is Ksh 25,000

## 1.3 The Continue Statement

In [5]:
# Example 1
# Using the continue statement we can stop the current iteration of the loop, 
# and continue with the next section of our code as shown
#

fruits = ["dates", "coconut", "passion"]

for x in fruits:
  if x == "coconut":
    continue 
  print(x)

dates
passion

In [6]:
# Example 2
# Iterating over a string
#

for val in "Moringa School":
    if val == "i":
        continue
    print(val)
print("The end")

M
o
r
n
g
a

S
c
h
o
o
l
The end

In [7]:
# Example 3
# 
mobile_phone = ["samsung", "doogee", "iphone", "wiko", "LG", "Panasonic", "Sony"]

for x in mobile_phone:  
    if x == 'samsung' or x == 'iphone': 
         continue
    print ('Checked Phone :', x)

Checked Phone : doogee
Checked Phone : wiko
Checked Phone : LG
Checked Phone : Panasonic
Checked Phone : Sony

### <font color="green">1.3 Challanges</font>

In [8]:
# Challenge 1
# Make changes to the code below to omit the month of July and August
# while displaying the no. of months
#

months = ["January ","February","March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]

for m in months:
	if m == 'July' or x == 'August': 
         continue
	print(m)

January
February
March
April
May
June
August
September
October
November
December

In [9]:
# Challenge 2
# Let's print out a word if it doesn't have the letter "e"
# Use the continue statement in your program
#

names = ['Jane', 'June', 'Thomas']
for m in names:
	if "e" in m: 
         continue
	print(m)

Thomas

In [33]:
# Challenge 3
# Given the numbers list below, print out the even numbers using the continue statement
# Hint: use modulo %
# 

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

for m in numbers:
  k = m%2
  if k ==1:
    continue
  print(m)

2
4
6
8
10

## 1.4 The Range() Function

In [40]:
# Example 1
# We iterate through a set of code a specified number of times using the range() function.
# Let's create a sequence of numbers from 0 to 5, and print each item in the sequence:
# 

for x in range(6):
  print(x)

0
1
2
3
4
5

In [41]:
# Example 2
# What happens when we have two parameters?
# 

for i in range(3, 9):
  print(i)

3
4
5
6
7
8

In [42]:
# Example 3
# What happens when we have three parameters as shown?
# 

for i in range(1, 20, 3):
  print(i)

1
4
7
10
13
16
19

### <font color="green">1.4 Challenges</font>

In [45]:
# Challenge 1
# Create a sequence of numbers from 3 to 61, but increment by 5:
#
for i in range(3, 61, 5):
  print(i)

3
8
13
18
23
28
33
38
43
48
53
58

In [46]:
# Challenge 2
# Create a program that prints out the even numbers within
# the range of 1 - 20
# 
for i in range(1, 20):
  k=i%2
  if k ==0:
    print(i)

2
4
6
8
10
12
14
16
18

In [49]:
# Challenge 3
# Create a sequence of numbers from 5 to -30, decrementing by 5
#
#
for i in range(5, -30, -5):
  print(i)

5
0
-5
-10
-15
-20
-25

## 1.5 Else

In [38]:
# Example 1
# When the loop condition of "for" or "while" statement fails 
# then code part in "else" is executed as shown below
#

for x in range(6):
  print(x)
else:
  print("Finished!")

0
1
2
3
4
5
Finished!

In [39]:
# Example 2
# In this example the code in the else block runs only 
# if the loop completes without encountering a break statement.
#

for i in range(3):
    password = input('Enter your password: ')
    if password == 'secret':
        print('You have guessed the password!')
        break
else:
    print('You have made 3 incorrect password attempts')

Enter your password: password
Enter your password: secret
You have guessed the password!

### <font color="green">1.5 Challanges</font>

In [44]:
# Challenge 1
# Let us iterate through and print out all even numbers from the numbers list below 
# in the same order they are received. We are not allowed toprint any numbers 
# that come after 237 in the sequence.
# 

numbers = [ 951, 402, 984, 651, 360, 69, 408, 319, 601, 485, 980, 507, 725, 547, 544,
    615, 83, 165, 141, 501, 263, 617, 865, 575, 219, 390, 984, 592, 236, 105, 942, 941,
    386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345,
    399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217,
    815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717,
    958, 609, 842, 451, 688, 753, 854, 685, 93, 857, 440, 380, 126, 721, 328, 753, 470,
    743, 527
]
for i in numbers:
  if i == 237:
    break
  elif i % 2 == 0:
    print(i)

402
984
360
408
980
544
390
984
592
236
942
386
462
418
344
236
566
978
328
162
758
918

In [22]:
# Challenge 2
# Write a program to find whether there is a word with the letter z from the list below
#

my_list = ["bawk", "bagawk", "a", "aa", "aazh", "aahed", "aahing", "aahs", "aal", "aalii", 
           "aaliis", "aals", "aardvark", "aardvarks", "aardwolf", "aardwolves", "aargh", 
           "aarrgh", "aarrghh", "aarti", "aartis", "aas", "aasvogel"]

for m in my_list:
  if "z" in m:
    print(m)

aazh

## 1.6 Nested For Loops

In [50]:
# Example 1
# You can use a loop inside another loop as shown below 
#

adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    print(x, y)

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry

In [56]:
# Example 2
# Iterating over multi dimension list i.e. lists in a list
#

# Creating a persons list
persons = [['Monica', 40], ['Mary', 15], ['Miriam', 20]]
  
for person in persons: 
  for value in person: 
    print(value)

Monica
40
Mary
15
Miriam
20

### <font color="green">1.6 Challenges</font>

In [64]:
# Challenge 1
# Iterate through the list of integers. In the outer loop, iterate through the numbers_list  
# and iterate through strings_list in the inner loop. 
# printing out 1 a b c 2 a b c 3 a b c
#

# Creating our lists
numbers_list = [1, 2, 3]
strings_list = ['a', 'b', 'c']

for x in numbers_list:
  print(x)
  for y in strings_list:
    print(y)

1
a
b
c
2
a
b
c
3
a
b
c

In [107]:
# Challenge 2
# Modify the code below to print out number of cars each of the billionares has 
# 

#Creating our lists
billionares = ['Jeff','Samuel','Donnah']       
cars = ['mercedes','porshe','hyundai'] 
numbers = [55, 24, 30]

for name in billionares:                     
  for count in numbers:
    count = count +1                         
    print(name," has "+str(count), "cars")

Jeff  has 56 cars
Jeff  has 25 cars
Jeff  has 31 cars
Samuel  has 56 cars
Samuel  has 25 cars
Samuel  has 31 cars
Donnah  has 56 cars
Donnah  has 25 cars
Donnah  has 31 cars

In [95]:
# Challenge 3
# Come up with of a question you can ask your friends. 
# Create a dictionary where each key is a person's name, 
# and each value is that person's response to your question.
# Store more three thn responses in your dictionary 
# and use a for loop to print out each person's response
#
my_dict = dict()

n= 3
for i in range (0,n):
   keys =input("Enter your Name:")
   value=input("What is the capital of Kenya?:")
   my_dict[keys]=[value]
print(my_dict)

Enter your Name:Brian
What is the capital of Kenya?:Nanyuki
Enter your Name:James
What is the capital of Kenya?:Nairobi
Enter your Name:John
What is the capital of Kenya?:Kisumu
{'Brian': ['Nanyuki'], 'James': ['Nairobi'], 'John': ['Kisumu']}