<font color="green">*To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

# Python Programming: Stratified Sampling Exercise

## Example

We are going to use the example we looked at in the overview. Our dataset is comprised of different heights of Moringa School students. It has 10,000 entries whereby 60% are female and 40% are Male. We are going to perform stratified sampling on this population so that we can get a sample of 1000 students which has the same proportion as the population.

**Import relevant Libraries**

In [2]:
import pandas as pd

**Load the Dataset**

Here is the dataset we are going to use in this example.[Dataset Download](https://drive.google.com/file/d/1ODcSRSs_isRKCAShFwnMrXdcphed9kYn/view?usp=sharing)

In [4]:
# Load the data into a panda dataframe
data= pd.read_csv('Gender_heights.csv')

# Check out the data
data

     gender         ht
0         F  55.398043
1         F  64.975468
2         F  70.591667
3         F  63.574479
4         F  62.535298
...     ...        ...
9995      M  91.485240
9996      M  94.842755
9997      M  98.096696
9998      M  91.478957
9999      M  88.849197

[10000 rows x 2 columns]

In [5]:
# Now we will confirm how many Female students and Male students are there in our dataset.
# To achieve this we will use pandas .value_count() method. This method outputs the number of times a value appears in a column.
data['gender'].value_counts()

F    6000
M    4000
Name: gender, dtype: int64

Now that we have confirmed that our popluation follows the correct proportion, we are going to first create a random sample of 1000 students without stratification just to see how it behaves.

In [7]:
# To create a random sample from a dataframe we use the pandas sample method. You can read more about it here.https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html
# We pass in an argument called frac which symbolises the fraction of the population we want to use as our sample

# Non stratified sample
non_strat_output = data.sample(frac=0.1) 

# check the proportion of the non_stratified sample
print(non_strat_output['gender'].value_counts())

F    589
M    411
Name: gender, dtype: int64

Run the code several times, taking note of the proportion of Female and Male. What do you notice?

When you run it several time, you'll notice that the proportion varies each time. Although it ranges closely to our desired proportion, its not quite the 60-40 proportion we want. To remedy it, this is where stratified sampling comes in handy.

Let's us create a stratified random sample and see how it behaves

In [8]:

# To create a stratified random sample we'll use pandas groupBy method. Basically what the method does is that it splits our dataset into sets and then applies a function on each subset.
# In our case, we are going to applies a function that puts each subset into a random sample with a size of 100. The beauty about this method is that it strictly maintains the populations proportion.

# Stratified sample
strat_output = data.groupby('gender', group_keys=False).apply(lambda grouped_subset : grouped_subset.sample(frac=0.1))

# proportion of the non_stratified sample
print(strat_output['gender'].value_counts())

# Check the stratified output
print(strat_output)

F    600
M    400
Name: gender, dtype: int64
     gender         ht
28        F  60.051298
529       F  63.229331
1190      F  59.360645
697       F  61.767897
3861      F  58.859349
...     ...        ...
7913      M  93.649738
8550      M  93.683843
9992      M  93.660974
6000      M  89.440562
7541      M  81.089048

[1000 rows x 2 columns]

## <font color="green">Challenges</font>

In [43]:
# Challenge 1
# ---
# Question: Moringa school is doing an analysis on how the students perform based on the different programmes that they offer.
# Given a dataset of 10000 students and you are told that 50% are Core students, 25% are Prep students and 25% are Pre-prep students. 
# Also in the dataset, 60% of the students are Female and the rest are Male. 
# You are tasked with creating a stratified random sample that represents that population.
# ---
# Dataset Source = https://drive.google.com/file/d/10THQj3iqund_D5tgypBdeKoc2FZ9pC0S/view?usp=sharing
# ---
# 
df = pd.read_csv('Moringa_Students_heights.csv')

# Check out the data
df

# Stratified sample for Core
core = df[df['programme'] =='Core']
core_output = core.groupby('gender', group_keys=False).apply(lambda grouped_subset : grouped_subset.sample(frac=0.1))

# proportion of the non_stratified sample
print(core_output['gender'].value_counts())

# Stratified sample for Prep
prep = df[df['programme'] =='Prep']
prep_output = prep.groupby('gender', group_keys=False).apply(lambda grouped_subset : grouped_subset.sample(frac=0.1))

# proportion of the non_stratified sample
print(prep_output['gender'].value_counts())

# Stratified sample for Pre-prep
pre_prep = df[df['programme'] =='Pre-prep']
pre_prep_output = pre_prep.groupby('gender', group_keys=False).apply(lambda grouped_subset : grouped_subset.sample(frac=0.1))

# proportion of the non_stratified sample
print(pre_prep_output['gender'].value_counts())

#combined sample
df_sample = pd.concat([core_output, prep_output,pre_prep_output])
df_sample.shape

F    299
M    201
Name: gender, dtype: int64
F    150
M    100
Name: gender, dtype: int64
F    150
M    100
Name: gender, dtype: int64

(1000, 3)

In [47]:
# Challenge 2
# ---
# Question: A wine company would like to perform some analysis on a variety of new red wines. 
# Select a stratified sample based on wine quality from the given dataset.
# ---
# Dataset 
url = "http://bit.ly/RedWinesDataset"
df = pd.read_csv(url)

# Check out the data
df

# Stratified sample
df_output = df.groupby('quality', group_keys=False).apply(lambda grouped_subset : grouped_subset.sample(frac=0.2))

# proportion of the non_stratified sample
print(df_output['quality'].value_counts())

# Check the stratified output
print(df_output)

5    136
6    128
7     40
4     11
8      4
3      2
Name: quality, dtype: int64
      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1505            6.7             0.760         0.02             1.8      0.078
899             8.3             1.020         0.02             3.4      0.084
1293            7.5             0.755         0.00             1.9      0.084
647             8.3             0.845         0.01             2.2      0.070
600             8.2             0.915         0.27             2.1      0.088
...             ...               ...          ...             ...        ...
442            15.6             0.685         0.76             3.7      0.100
828             7.8             0.570         0.09             2.3      0.065
1449            7.2             0.380         0.31             2.0      0.056
278            10.3             0.320         0.45             6.4      0.073
455            11.3             0.620         0.67             5.2      0.086

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1505                  6.0                  12.0  0.99600  3.55       0.63
899                   6.0                  11.0  0.99892  3.48       0.49
1293                  6.0                  12.0  0.99672  3.34       0.49
647                   5.0                  14.0  0.99670  3.32       0.58
600                   7.0                  23.0  0.99620  3.26       0.47
...                   ...                   ...      ...   ...        ...
442                   6.0                  43.0  1.00320  2.95       0.68
828                  34.0                  45.0  0.99417  3.46       0.74
1449                 15.0                  29.0  0.99472  3.23       0.76
278                   5.0                  13.0  0.99760  3.23       0.82
455                   6.0                  19.0  0.99880  3.22       0.69

      alcohol  quality
1505     9.95        3
899     11.00        3
1293     9.70        4
647     11.00        4
600     10.00        4
...       ...      ...
442     11.20        7
828     12.70        8
1449    11.30        8
278     12.60        8
455     13.40        8

[321 rows x 12 columns]

In [51]:
pip install --upgrade xlrd

Requirement already satisfied: xlrd in /usr/local/lib/python3.7/dist-packages (1.1.0)
Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 96 kB 4.2 MB/s
Installing collected packages: xlrd
  Attempting uninstall: xlrd
    Found existing installation: xlrd 1.1.0
    Uninstalling xlrd-1.1.0:
      Successfully uninstalled xlrd-1.1.0
Successfully installed xlrd-2.0.1

In [25]:
# Challenge 3
# ---
# Question: You have been provided with a list of employees of a certain company with some details about their gender (male/female) 
# and their type of employment (full-time/part-time). The HR team wants to conduct a survey on the working condition 
# that will be representative of the general opinion without interviewing every employee. 
# They request you conduct stratified sampling before any analysis is done. 
# ---
# Dataset 
url = "http://bit.ly/StratifiedEmployeeDataset"
# ---
# Hint: Perform EDA first
# ---
df =pd.read_excel("employee dataset.xls")

#checking the shape
print(df.shape)

# Checking null values
print(df.isnull().sum())

#checking data types
print(df.dtypes)

# Value counts
df1 = df['Gender'].groupby(by= df.Time).value_counts()
print(df1)

# Stratified sample for Full-time
ft = df[df['Time'] =='Full-time']
ft_output = ft.groupby('Gender', group_keys=False).apply(lambda grouped_subset : grouped_subset.sample(frac=0.2))

# proportion of the non_stratified sample
print(ft_output['Gender'].value_counts())

# Stratified sample for Prep
pt = df[df['Time'] =='Part-time']
pt_output = pt.groupby('Gender', group_keys=False).apply(lambda grouped_subset : grouped_subset.sample(frac=0.2))

# proportion of the non_stratified sample
print(pt_output['Gender'].value_counts())

#combined sample
df_sample = pd.concat([ft_output, pt_output])
print(df_sample.shape)
df_sample

(97, 4)
Employee    0
Gender      0
Time        0
Strata      0
dtype: int64
Employee    object
Gender      object
Time        object
Strata      object
dtype: object
Time       Gender
Full-time  Male      43
           Female    21
Part-time  Female    24
           Male       9
Name: Gender, dtype: int64
Male      9
Female    4
Name: Gender, dtype: int64
Female    5
Male      2
Name: Gender, dtype: int64
(20, 4)

   Employee  Gender       Time Strata
89    Em090  Female  Full-time     FF
23    Em024  Female  Full-time     FF
30    Em031  Female  Full-time     FF
52    Em053  Female  Full-time     FF
45    Em046    Male  Full-time     MF
54    Em055    Male  Full-time     MF
6     Em007    Male  Full-time     MF
0     Em001    Male  Full-time     MF
55    Em056    Male  Full-time     MF
25    Em026    Male  Full-time     MF
94    Em095    Male  Full-time     MF
58    Em059    Male  Full-time     MF
75    Em076    Male  Full-time     MF
70    Em071  Female  Part-time     FP
67    Em068  Female  Part-time     FP
5     Em006  Female  Part-time     FP
60    Em061  Female  Part-time     FP
63    Em064  Female  Part-time     FP
1     Em002    Male  Part-time     MP
38    Em039    Male  Part-time     MP